#include-once

; Renderer event types
Global Enum $MOGRAPH_EV_TIMEEQUAL = 1, _
			$MOGRAPH_EV_TIMELESS, _
			$MOGRAPH_EV_TIMELESSEQUAL, _
			$MOGRAPH_EV_TIMEGREATER, _
			$MOGRAPH_EV_TIMEGREATEREQUAL

; String animation types
Global Enum $MOGRAPH_TXTANIM_LEFTTORIGHT = 1, _
			$MOGRAPH_TXTANIM_RIGHTTOLEFT, _
			$MOGRAPH_TXTANIM_RANDOMLTR, _
			$MOGRAPH_TXTANIM_RANDOMRTL